Fix cFS/workflows#177

diff --git a/.github/workflows/build-doc-reusable.yml b/.github/workflows/build-doc-reusable.yml
--- a/.github/workflows/build-doc-reusable.yml
+++ b/.github/workflows/build-doc-reusable.yml
@@ -23,7 +23,7 @@ on:
         description: Build the PDF
         type: boolean
         required: false
-        default: true
+        default: false
       deploy:
         description: Deploy archived PDF to gh-pages
         type: boolean
@@ -34,6 +34,14 @@ on:
         type: boolean
         required: false
         default: true
+      defs:
+        description: '*_defs directory'
+        type: string
+        required: false
+        default: 'sample_defs'
+
+env:
+  WORK_PATH: ${{ github.workspace }}
 
 # Force bash to apply pipefail option so pipeline failures aren't masked
 defaults:
@@ -61,6 +69,7 @@ jobs:
     if: ${{ needs.checks-for-duplicates.outputs.should_skip != 'true' || contains(github.ref, 'main') }}
     name: Build Documentation
     runs-on: ubuntu-22.04
+    container: ghcr.io/arielswalker/cfsbuildenv-doxygen:latest
 
     strategy:
       fail-fast: false
@@ -79,41 +88,12 @@ jobs:
         if: ${{ inputs.cache-key != '' }}
         uses: actions/cache@v4
         with:
-          path: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/*
+          path: ${{ env.WORK_PATH }}/
           key: ${{ inputs.cache-key }}
 
-      - name: Checkout Bundle Main
-        if: ${{ inputs.app-name != '' }}
-        uses: actions/checkout@v4
-        with:
-          submodules: true
-          repository: nasa/cFS
-
-      - name: Checkout Repo
-        if: ${{ inputs.app-name != '' }}
-        uses: actions/checkout@v4
-        with:
-          path: apps/${{ inputs.app-name }}
-
-      - name: Copy Files
-        run: |
-          cp ./cfe/cmake/Makefile.sample Makefile
-          cp -r ./cfe/cmake/sample_defs sample_defs
-
-      - name: Add Repo To Build
-        if: ${{ inputs.app-name != '' }}
-        run: echo 'set(MISSION_GLOBAL_APPLIST ${{ inputs.app-name }})' >> sample_defs/targets.cmake
-
-      - name: Make Prep
-        run: make prep
-
-      - name: Install Doxygen Dependencies
-        run: sudo apt-get update && sudo apt-get install doxygen graphviz -y
-
-      - name: Install PDF Generation Dependencies
-        if: ${{ inputs.buildpdf == true }}
-        run: |
-          sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
+      - name: Set up app source
+        if: steps.cache-src-bld.outputs.cache-hit != 'true'
+        uses: arielswalker/cFS/actions/setup-app@fix-cfs/workflows#177
 
       - name: Generate OSAL header list
         if: ${{ inputs.needs_osal_api == true }}
@@ -137,21 +117,25 @@ jobs:
         run: |
           if [[ -s ${{ matrix.target }}_stderr.txt ]]; then
             cat ${{ matrix.target }}_stderr.txt
-            exit -1
+            exit 1
           fi
 
       - name: Check For Document Warnings
         run: |
           if [[ -s ${{ matrix.target }}-warnings.log ]]; then
             cat ${{ matrix.target }}-warnings.log
-            exit -1
+            exit 1
           fi
 
       - name: Generate PDF
         if: ${{ inputs.buildpdf == true }}
         run: |
-          make -C ./build/docs/${{ matrix.target }}/latex
-          mkdir deploy
+          if ! make LATEX_CMD="pdflatex -file-line-error -halt-on-error" -C ./build/docs/${{ matrix.target }}/latex > pdflatex.log; then
+            echo "Errors reported, tail of latex output follows"
+            tail -100 pdflatex.log
+            exit -1
+          fi
+          mkdir -p deploy
           mv ./build/docs/${{ matrix.target }}/latex/refman.pdf ./deploy/${{ matrix.target }}.pdf
           # Could add pandoc and convert to github markdown
           # pandoc ${{ matrix.target }}.pdf -t gfm
@@ -164,7 +148,7 @@ jobs:
           path: ./deploy/${{ matrix.target }}.pdf
 
       - name: Deploy to GitHub
-        if: ${{ inputs.deploy == true }}
+        if: ${{ inputs.buildpdf == true && inputs.deploy == true }}
         uses: JamesIves/github-pages-deploy-action@v4
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
